version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: moneybuddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: gunicorn moneybuddy_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=moneybuddy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GROQ_API_KEY=YOUR_GROQ_KEY_HERE
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    stdin_open: true
    ports:
      - "3000:3000"
